// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelInstallTask(arg1) {
  return window['go']['main']['App']['CancelInstallTask'](arg1);
}

export function CreateInstallPlan(arg1) {
  return window['go']['main']['App']['CreateInstallPlan'](arg1);
}

export function GetInstallTask(arg1) {
  return window['go']['main']['App']['GetInstallTask'](arg1);
}

export function ProbeProxy(arg1) {
  return window['go']['main']['App']['ProbeProxy'](arg1);
}

export function ScanEnvironment() {
  return window['go']['main']['App']['ScanEnvironment']();
}

export function StartInstall(arg1) {
  return window['go']['main']['App']['StartInstall'](arg1);
}

export function UseDirectConnection() {
  return window['go']['main']['App']['UseDirectConnection']();
}
