// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {proxy} from '../models';
import {domain} from '../models';

export function ProbeProxy(arg1:number):Promise<proxy.Result>;

export function ScanEnvironment():Promise<domain.EnvironmentSnapshot>;

export function UseDirectConnection():Promise<void>;
