// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyAPIPlan(arg1) {
  return window['go']['main']['App']['ApplyAPIPlan'](arg1);
}

export function CancelInstallTask(arg1) {
  return window['go']['main']['App']['CancelInstallTask'](arg1);
}

export function CreateAPIApplyPlan(arg1, arg2) {
  return window['go']['main']['App']['CreateAPIApplyPlan'](arg1, arg2);
}

export function CreateInstallPlan(arg1) {
  return window['go']['main']['App']['CreateInstallPlan'](arg1);
}

export function DeleteAPIProfile(arg1) {
  return window['go']['main']['App']['DeleteAPIProfile'](arg1);
}

export function GetAPICompatibility(arg1) {
  return window['go']['main']['App']['GetAPICompatibility'](arg1);
}

export function GetInstallTask(arg1) {
  return window['go']['main']['App']['GetInstallTask'](arg1);
}

export function ListAPIProfiles() {
  return window['go']['main']['App']['ListAPIProfiles']();
}

export function ProbeAPIProfile(arg1) {
  return window['go']['main']['App']['ProbeAPIProfile'](arg1);
}

export function ProbeProxy(arg1) {
  return window['go']['main']['App']['ProbeProxy'](arg1);
}

export function SaveAPIProfile(arg1) {
  return window['go']['main']['App']['SaveAPIProfile'](arg1);
}

export function ScanEnvironment() {
  return window['go']['main']['App']['ScanEnvironment']();
}

export function StartInstall(arg1) {
  return window['go']['main']['App']['StartInstall'](arg1);
}

export function UseDirectConnection() {
  return window['go']['main']['App']['UseDirectConnection']();
}
