// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {profiles} from '../models';
import {install} from '../models';
import {removal} from '../models';
import {history} from '../models';
import {proxy} from '../models';
import {domain} from '../models';

export function ApplyAPIPlan(arg1:string):Promise<profiles.ApplyBatchResult>;

export function CancelInstallTask(arg1:string):Promise<void>;

export function ClearHistory():Promise<void>;

export function CreateAPIApplyPlan(arg1:string,arg2:Array<string>):Promise<profiles.ApplyPlan>;

export function CreateInstallPlan(arg1:string):Promise<install.Plan>;

export function CreateRemovalPlan(arg1:string):Promise<removal.Plan>;

export function DeleteAPIProfile(arg1:string):Promise<void>;

export function GetAPICompatibility(arg1:string):Promise<Array<profiles.TargetCompatibility>>;

export function GetInstallTask(arg1:string):Promise<install.Task>;

export function LaunchComponent(arg1:string,arg2:string):Promise<void>;

export function ListAPIProfiles():Promise<Array<profiles.Profile>>;

export function ListHistory():Promise<Array<history.Entry>>;

export function ProbeAPIProfile(arg1:string):Promise<profiles.ProbeResult>;

export function ProbeProxy(arg1:number):Promise<proxy.Result>;

export function RemoveComponent(arg1:string):Promise<removal.Result>;

export function SaveAPIProfile(arg1:profiles.Input):Promise<profiles.Profile>;

export function ScanEnvironment():Promise<domain.EnvironmentSnapshot>;

export function StartInstall(arg1:string):Promise<install.Task>;

export function UseDirectConnection():Promise<void>;
